// <auto-generated />
using ArcticaAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcticaAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("ArcticaAPI.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HospitalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HospitalId");

                    b.HasIndex("PositionId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 33,
                            FName = "Алина",
                            HospitalId = 1,
                            PositionId = 1,
                            SName = "Фролова",
                            TName = "Васильевна"
                        },
                        new
                        {
                            Id = 2,
                            Age = 76,
                            FName = "Анна",
                            HospitalId = 1,
                            PositionId = 2,
                            SName = "Попова",
                            TName = "Семёновна"
                        },
                        new
                        {
                            Id = 3,
                            Age = 64,
                            FName = "Ветров",
                            HospitalId = 2,
                            PositionId = 2,
                            SName = "Максим",
                            TName = "Васильевич"
                        });
                });

            modelBuilder.Entity("ArcticaAPI.Models.Hospital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CarPark")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hospitals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Суворова, 1, Архангельск, Архангельская обл.",
                            CarPark = true,
                            Name = "Первая городская имени Волосевича"
                        },
                        new
                        {
                            Id = 2,
                            Address = "просп. Ломоносова, 292, Архангельск, Архангельская обл.",
                            CarPark = false,
                            Name = "ГБУЗ АО 'Архангельская областная клиническая больница'"
                        });
                });

            modelBuilder.Entity("ArcticaAPI.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patient");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 33,
                            Diagnosis = "Гипертония",
                            FName = "Василий",
                            SName = "Петров",
                            TName = "Евгеньевич"
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            Diagnosis = "Аритмия",
                            FName = "Мария",
                            SName = "Семёнова",
                            TName = "Анатольевна"
                        },
                        new
                        {
                            Id = 3,
                            Age = 54,
                            Diagnosis = "Рак",
                            FName = "Арсен",
                            SName = "Петров",
                            TName = "Максимович"
                        });
                });

            modelBuilder.Entity("ArcticaAPI.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Charge")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Positions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Charge = "Лечить сердце и сосуды",
                            Name = "Кардиолог"
                        },
                        new
                        {
                            Id = 2,
                            Charge = "Лечить всё",
                            Name = "Терапевт"
                        });
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.Property<int>("DoctorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DoctorsId", "PatientsId");

                    b.HasIndex("PatientsId");

                    b.ToTable("DoctorPatient", (string)null);

                    b.HasData(
                        new
                        {
                            DoctorsId = 2,
                            PatientsId = 1
                        },
                        new
                        {
                            DoctorsId = 2,
                            PatientsId = 2
                        },
                        new
                        {
                            DoctorsId = 3,
                            PatientsId = 3
                        });
                });

            modelBuilder.Entity("ArcticaAPI.Models.Doctor", b =>
                {
                    b.HasOne("ArcticaAPI.Models.Hospital", "Hospital")
                        .WithMany("Doctors")
                        .HasForeignKey("HospitalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcticaAPI.Models.Position", "Position")
                        .WithMany("Doctors")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hospital");

                    b.Navigation("Position");
                });

            modelBuilder.Entity("DoctorPatient", b =>
                {
                    b.HasOne("ArcticaAPI.Models.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArcticaAPI.Models.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ArcticaAPI.Models.Hospital", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ArcticaAPI.Models.Position", b =>
                {
                    b.Navigation("Doctors");
                });
#pragma warning restore 612, 618
        }
    }
}
